=== aptem4ka/Task3/src/main/resources/menu.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.menu.epam.com/menu"
        xmlns:tns="http://www.menu.epam.com/menu"
        elementFormDefault="qualified">

    <element name="menu">
        <complexType>
            <sequence maxOccurs="unbounded">
                <element name="food" type="tns:food"/>
            </sequence>
        </complexType>
    </element>


    <complexType name="food">
        <sequence>
            <element name="name" type="string"/>
            <element name="description" type="string" minOccurs="0"/>
            <element name="portion" type="string"/>
            <element name="image" type="tns:imageURL" minOccurs="0"/>
            <element name="options" type="tns:optionsType"/>
            <element name="ingridients" type="tns:ingridientsType"/>
        </sequence>
        <attribute name="id" use="required"/>
        <attribute name="type" use="required"/>
    </complexType>


    <simpleType name="prices">
        <restriction base="string"/>
    </simpleType>

    <attributeGroup name="priceAttr">
        <attribute name="option" type="string" use="optional"/>
        <attribute name="value" type="tns:priceValue" use="required"/>
    </attributeGroup>

    <simpleType name="priceValue">
        <restriction base="string">
            <pattern value="(\d)+(\.(\d){1,2})?\$"/>
        </restriction>
    </simpleType>

    <simpleType name="imageURL">
        <restriction base="string">
            <pattern value="(.)+\.(gif|jpg|jpeg|bmp|png)"/>
        </restriction>
    </simpleType>

    <complexType name="optionsType">
        <sequence minOccurs="1" maxOccurs="unbounded">
            <element name="price">
                <complexType>
                    <attributeGroup ref="tns:priceAttr"/>
                </complexType>
            </element>
        </sequence>
    </complexType>

    <complexType name="ingridientsType">
        <sequence maxOccurs="unbounded">
            <element name="ingridient">
                <complexType>
                    <attribute name="name" type="string"/>
                </complexType>
            </element>
        </sequence>
    </complexType>

</schema>

=== aptem4ka/Task3/src/main/resources/menu.xml
<?xml version="1.0" encoding="UTF-8" ?>
<menu xmlns="http://www.menu.epam.com/menu"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://menu.epam.com/menu menu.xsd">



    <food id="1" type="cold_snack">
        <name>Ассорти рыбное</name>
        <description>Слабосоленая форель, семга</description>
        <portion>10/100/200</portion>
        <image>test.jpg</image>
        <options>
            <price value="4.35$"/>
        </options>
        <ingridients>
            <ingridient name="Форель"/>
            <ingridient name="Семга"/>
        </ingridients>
    </food>

    <food id="2" type="cold_snack">
        <name>Тарталетки с красной икрой</name>
        <description>Тарталетки с красной икрой</description>
        <portion>60/50</portion>
        <image>test.jpg</image>
        <options>
            <price value="11$"/>
        </options>
        <ingridients>
            <ingridient name="Тарталетки"/>
            <ingridient name="Икра красная"/>
        </ingridients>
    </food>

    <food id="3" type="cold_snack">
        <name>Закуска по-русски</name>
        <description>Кусочки атлантической сельди с отварным картофелем, луком, лимоном и зеленью</description>
        <portion>70/50/2/10</portion>
        <image>test.jpg</image>
        <options>
            <price value="11$"/>
        </options>
        <ingridients>
            <ingridient name="Селедка"/>
            <ingridient name="Картофель"/>
            <ingridient name="Лук"/>
            <ingridient name="Лимон"/>
            <ingridient name="Укроп"/>
            <ingridient name="Петрушка"/>
        </ingridients>
    </food>

    <food id="4" type="cold_snack">
        <name>Куриный рулет</name>
        <description>Куриный рулет собственного производства</description>
        <portion>100/5</portion>
        <image>test.jpg</image>
        <options>
            <price value="7$"/>
        </options>
        <ingridients>
            <ingridient name="Куриное филе"/>
            <ingridient name="Зелень"/>
        </ingridients>
    </food>

    <food id="5" type="cold_snack">
        <name>Бастурма</name>
        <description>Вяленая нарезка из говяжьего мяса</description>
        <portion>50/5</portion>
        <image>test.jpg</image>
        <options>
            <price value="5.33$"/>
        </options>
        <ingridients>
            <ingridient name="Говядина"/>
            <ingridient name="Зелень"/>
        </ingridients>
    </food>

    <food id="6" type="cold_snack">
        <name>Ассорти мясное</name>
        <description>Нарезка из буженины, бастурмы, куриного рулета собственного производства и колбасы</description>
        <portion>100/30</portion>
        <image>test.jpg</image>
        <options>
            <price value="11.99$"/>
        </options>
        <ingridients>
            <ingridient name="Буженина"/>
            <ingridient name="Бастурма"/>
            <ingridient name="Куриный рулет"/>
            <ingridient name="Колбаса"/>
        </ingridients>
    </food>

    <food id="7" type="cold_snack">
        <name>Язык отварной</name>
        <description>Нарезка нежного говяжьего языка, подается с хреном</description>
        <portion>80/20/1</portion>
        <image>test.jpg</image>
        <options>
            <price value="13.50$"/>
        </options>
        <ingridients>
            <ingridient name="Говяжий язык"/>
            <ingridient name="Хрен"/>
            <ingridient name="Зелень"/>
        </ingridients>
    </food>

    <food id="8" type="cold_snack">
        <name>Ассорти баклажаны</name>
        <description>Жареные баклажаны</description>
        <portion>100/5</portion>
        <image>test.jpg</image>
        <options>
            <price option="с помидорами" value="5.33$"/>
            <price option="с чесноком" value="6.79$"/>
            <price option="с орехами" value="7$"/>
        </options>
        <ingridients>
            <ingridient name="Баклажаны"/>
            <ingridient name="Помидоры"/>
            <ingridient name="Чеснок"/>
            <ingridient name="Орехи"/>
        </ingridients>
    </food>

    <food id="9" type="cold_snack">
        <name>Соленья по-домашнему</name>
        <description>Маринованные овощи</description>
        <portion>150/10</portion>
        <image>test.jpg</image>
        <options>
            <price value="5.30$"/>
        </options>
        <ingridients>
            <ingridient name="Маринованные огурцы"/>
            <ingridient name="Маринованные помидоры"/>
            <ingridient name="Маринованные кабачки"/>
        </ingridients>
    </food>

    <food id="10" type="cold_snack">
        <name>Бабушкины угощения</name>
        <description>Ассорти из маринованных грибов</description>
        <portion>120/20/10</portion>
        <image>test.jpg</image>
        <options>
            <price value="8$"/>
        </options>
        <ingridients>
            <ingridient name="Маринованные лисички"/>
            <ingridient name="Маринованные боровики"/>
            <ingridient name="Маринованные белые грибы"/>
        </ingridients>
    </food>

    <food id="11" type="cold_snack">
        <name>Сырная тарелка</name>
        <description>Смесь самых разнообразных сыров</description>
        <portion>100/5</portion>
        <image>test.jpg</image>
        <options>
            <price value="10.50$"/>
        </options>
        <ingridients>
            <ingridient name="Сыр чедер"/>
            <ingridient name="Сыр дор блю"/>
            <ingridient name="Сыр мраморный"/>
        </ingridients>
    </food>

    <food id="12" type="hot_snack">
        <name>Лобио с шампиньонами</name>
        <description>Фасоль с шампиньонами и грецким орехом</description>
        <portion>150/5</portion>
        <image>test.jpg</image>
        <options>
            <price value="9.44$"/>
        </options>
        <ingridients>
            <ingridient name="Фасоль"/>
            <ingridient name="Шампиньоны"/>
            <ingridient name="Грецкий Орех"/>
        </ingridients>
    </food>
    <food id="13" type="hot_snack">
        <name>Жульен</name>
        <description>Жульен</description>
        <portion>120/1</portion>
        <image>test.jpg</image>
        <options>
            <price option="с курицей" value="11.35$"/>
            <price option="с грибами" value="5.35$"/>
        </options>
        <ingridients>
            <ingridient name="Фасоль"/>
            <ingridient name="Шампиньоны"/>
            <ingridient name="Грецкий Орех"/>
        </ingridients>
    </food>

    <food id="14" type="hot_snack">
        <name>Ахтамар мясной</name>
        <description>Колбаса, ветчина, буженина, сыр, запеченые на мангале в лаваше</description>
        <portion>1 шт.</portion>
        <image>test.jpg</image>
        <options>
            <price value="5$"/>
        </options>
        <ingridients>
            <ingridient name="Колбаса"/>
            <ingridient name="Ветчина"/>
            <ingridient name="Буженина"/>
            <ingridient name="Сыр"/>
            <ingridient name="Лаваш"/>
        </ingridients>
    </food>

    <food id="15" type="hot_snack">
        <name>Сюрприз</name>
        <description></description>
        <portion>1 шт.</portion>
        <image>test.jpg</image>
        <options>
            <price value="7$"/>
        </options>
        <ingridients>
            <ingridient name="Свинина"/>
            <ingridient name="Говядина"/>
            <ingridient name="Зелень"/>
        </ingridients>
    </food>

    <food id="16" type="hot_snack">
        <name>Креветки</name>
        <description>Креветки</description>
        <portion>120/30</portion>
        <image>test.jpg</image>
        <options>
            <price option="жареные" value="4.35$"/>
            <price option="отварные" value="4.50$"/>
        </options>
        <ingridients>
            <ingridient name="Королевские креветки"/>
        </ingridients>
    </food>
    <food id="17" type="hot_snack">
        <name>Мидии по-турецки</name>
        <description>Мидии, фаршированные сыром и грецким орехом</description>
        <portion>150/30</portion>
        <image>test.jpg</image>
        <options>
            <price value="10$"/>
        </options>
        <ingridients>
            <ingridient name="Мидии"/>
            <ingridient name="Сыр"/>
            <ingridient name="Грецкий орех"/>
        </ingridients>
    </food>





</menu>
